### ISSUE TITLE
How to set Connection parameters for BLE device

### ISSUE THREAD

**Issue by prachisg11** [tbrushwyler/Xamarin.BluetoothLE#21]
Can we specify connection parameters like connection interval, connection event, etc to increase the throughput of the BLE device, using Xamarin.BluetoothLE library? CharacteristicPropertyType do not have these properties.

**Comment by tbrushwyler** [comment]
No, these connection parameters must be set by the BLE peripheral. Android and iOS do not support setting these parameters from the central.
